### ISSUE TITLE
next prev not working

### ISSUE THREAD

**Issue by quasiperfect** [elboletaire/tabbedcontent#12]
hi

when i try to use next and previous next jumps to first tab and previous to last

please see this link i manage to reduce the code
the problem if if there are other li with the class active it doesn't work even when you specify what links target the tabs

http://codepen.io/anon/pen/MwKeqw

**Comment by elboletaire** [comment]
It seems to be due to the `active` class: http://codepen.io/anon/pen/xGZpea

I will take a further look into it during this week.
