### ISSUE TITLE
page jump on click on active tab link and if scrollbar present

### ISSUE THREAD

**Issue by quasiperfect** [elboletaire/tabbedcontent#13]
hi 

is there any way to stop the page jump on click on active tab link and if scrollbar present

test here

http://codepen.io/anon/pen/MwKeqw

**Comment by elboletaire** [comment]
You can add `pointer-events: none` to your active links disabling it's default behavior:

```css
li.active {
  pointer-events: none;
}
```

http://codepen.io/anon/pen/WvrdWo

**Comment by quasiperfect** [comment]
thanks for you help and your work
