### ISSUE TITLE
disable history

### ISSUE THREAD

**Issue by tsarma** [elboletaire/tabbedcontent#16]
Is there a way to disable HTML5 history API? What speaks against it?

**Comment by elboletaire** [comment]
Sorry for the delay.

Why would you like to disable it? I don't see any problem in creating a toggle for it.

**Comment by tsarma** [comment]
Hi there,
Basically Tap menu is nice, but I wanted to keep the browser back button to default function. By that I mean, one should be able to previous page when one clicks browser back button.

**Comment by elboletaire** [comment]
Hi @tsarma I'll try to do it when I can. BTW, I accept merge requests. So feel free to do it by yourself :)
