### ISSUE TITLE
Browser scrolling

### ISSUE THREAD

**Issue by sigismund** [elboletaire/tabbedcontent#18]
I have a problem with browser scrolling from tab button to button target. 

When I click on link Chrome browser scrolls to anchored ID, while in Firefox scrolling is disabled. 

Is there any way to disable browser scrolling in Chrome?

EDIT:
I already tried to add 'pointer-events: none' to the '.active' tab, but it doesn't work

**Comment by elboletaire** [comment]
The examples provided also have the scrolling issue? Because I'm trying it (using chromium 45.0.2454.101 Ubuntu 15.10 64bit) and I don't have the issue.

Please, tell me if the [bootstrap example](http://elboletaire.github.io/tabbedcontent/demos/bootstrap.html) makes your browser scroll.

**Comment by sigismund** [comment]
No, on this example it works ok. 
Unless I add so much html content after div.tabscontent that makes browser scrollbar visible.

**Comment by elboletaire** [comment]
Then you answered your own question... If my code is working there's some problem with yours.

Take a look to my examples CSS and to how I've added the `pointer-events: none` as this is the way I fixed it for chrome.

> Unless I add so much html content after div.tabscontent that makes browser scrollbar visible. 

But.. aren't we talking about your browser scrolling down? Scrollbars visiblity has nothing to do with the "browser scrolling" issue that you described in your first comment.

**Comment by sigismund** [comment]
I am not quite sure we understand each other.

Sample code, works because there is only so much content, but if tab is positioned onto site with height greater than viewport height is, anchor link jumping will occur. 

If you don't consider this to be a bug you should probably write into readme file, that this plugin is meant to be used as main navigation/without any other HTML code around it. Just my opinion.

**Comment by sigismund** [comment]
I didn't notice before that someone before me added a similar issue. 
I tested your response code (http://codepen.io/anon/pen/WvrdWo) in Chrome (46.0.2490.80 - Windows) and my page still scrolls down to tab with clicked id.

**Comment by elboletaire** [comment]
> I didn't notice before that someone before me added a similar issue.
I tested your response code (http://codepen.io/anon/pen/WvrdWo) in Chrome (46.0.2490.80 - Windows) and my page still scrolls down to tab with clicked id.

No, that's not the same issue.

> I am not quite sure we understand each other.

I've understood you... I've created this example specially for you. I've tried it on chrome and I don't have any issue with the scroll (look how I added a lot of `br` to move the content down):

http://jsfiddle.net/vnotugj0/

Does it work for you? I've tried it with the exact same chrome version I used yesterday (chromium 45.0.2454.101 Ubuntu 15.10 64bit) and it works as expected.

**Comment by sigismund** [comment]
In that case it works, unless I move those `br` tags bellow content as I did in demo and video.

Here is updated version of your example example with which I am having problems (try clicking on 2nd tab and then switching back to 1st):
http://jsfiddle.net/vnotugj0/1/

**Comment by elboletaire** [comment]
Dude, seriously.. I'm not having that issue xDDD

Check my screencast: https://www.dropbox.com/s/hxtsnegzm3ta031/tabbedcontent.ogv?dl=0

As you can see the scrollbar only moves when I directly move it (I move it so you can see that it works in any position).

Then... if you have issues with this same example, it could be due to a chrome bug (that's why I use firefox... I've found too much chrome bugs lately... I mean, a LOT of bugs).

**Comment by sigismund** [comment]
Damn. 
I totally understand you, but the problem are visitors who are using it...

It seems I will have to go annoy someone else (chrome bugtracker her I come). 

Thanks for your time.

**Comment by elboletaire** [comment]
You're welcome!

I'm glad to see there's people using my plugin :smile:

**Comment by elboletaire** [comment]
BTW, if you finally find a solution, be free to post it here to help others :smiley:

**Comment by elboletaire** [comment]
Hey @sigismund I've made some changes to the plugin (currently under `develop` branch) to add an option to disable the history api and now the issue you were having should be definitely fixed.

**Comment by elboletaire** [comment]
The changes have been published to [v1.6.0](https://github.com/elboletaire/tabbedcontent/releases/tag/v1.6.0)

**Comment by sigismund** [comment]
Sorry for delay, I wasn't 'online'.

As mater of fact, I did hack to solve that problem:
```
var mytabs = $('.tab-container').tabbedContent({ ...
```

and after that:
```
$(document).on('click', 'ul.tabs > li > a', function(e){
  e.preventDefault();
  mytabs.switch($(this).parent().index());
});
```
Not the prettiest solution but it works. :)

Tnx for that option to disable history, it could still come in handy. :)

**Comment by elboletaire** [comment]
Hehe, then download the latest version because that is what I've done now :)

Look: https://github.com/elboletaire/tabbedcontent/blob/master/tabbedcontent.js#L308

:smile:
