### ISSUE TITLE
Suggest Bootstrap tab overflow plugin (Many Tabs)

### ISSUE THREAD

**Issue by cyberzilla** [elboletaire/tabbedcontent#19]
how to fix this?
![before](https://cloud.githubusercontent.com/assets/1154922/11437809/8f664b44-952b-11e5-957a-fb6214c588bf.jpg)

become this?
![after](https://cloud.githubusercontent.com/assets/1154922/11437827/ad739c68-952b-11e5-9013-83eb27b4e44f.jpg)

**Comment by elboletaire** [comment]
Just to ensure, you want that arrows for moving between all the available tabs, right?

**Comment by cyberzilla** [comment]
If there are multiple tabs, the tab will automatically wrapping as the previous image, I want just one line of tabs as the next image, maybe like firefox tabs, thanks for help

![this](https://cloud.githubusercontent.com/assets/1154922/11449318/3281c126-95ab-11e5-9b4d-853400e86f86.png)

**Comment by elboletaire** [comment]
Sorry but this is a really huge extension of the plugin and I want my plugin to be lightweight. 

I could write an external library but I think that is useless taking in mind that there are a lot of libraries out there that can do that work. Search for any carousel plugin and you'll be able to do what you wanna do.

**Comment by elboletaire** [comment]
When I said that there were libraries to do that I was thinking in carousel plugins (like [one](http://getbootstrap.com/javascript/#carousel) [of](https://github.com/sachinchoolur/lightslider) [these](http://bxslider.com/)).

But now I see that you starred [a jquery plugin for scrolling tabs](http://joshreed.github.io/jQuery-ScrollTabs/). That's really nice for this purpose! I didn't know about it.

I'll add it to the readme so others know about it :smiley:

**Comment by cyberzilla** [comment]
"a jquery plugin for scrolling tabs" is not support bootstrap https://github.com/joshreed/jQuery-ScrollTabs/issues/4

**Comment by elboletaire** [comment]
Then you can use any of the ones linked above:

http://getbootstrap.com/javascript/#carousel
https://github.com/sachinchoolur/lightslider
http://bxslider.com/
