### ISSUE TITLE
api.switch doesn't change hash

### ISSUE THREAD

**Issue by tpaksu** [elboletaire/tabbedcontent#31]
Hi, 

I guess `api.switch` on init event doesn't change the addressbar hash, which may be a problem on page refreshes. Does anybody experienced this on init event? or is it just me?

**Comment by elboletaire** [comment]
Can you please add a peace of code or, much better, a jsfiddle, showing the problem?

**Comment by tpaksu** [comment]
jsfiddle won't allow me to refresh the page with hash. I'll prepare an example on my server.

**Comment by tpaksu** [comment]
**Test Address:** 
http://rettica.com/personal/tabs/

**Initialization Code:**
```
$(".tabscontent").tabbedContent({
    onInit: function(api) {
        if (api.getCurrent() == $("a[href='#tab-n']").parent("li").index()) {
            api.switch(0);
        }
    }
});
```

**Steps to reproduce:**
1. click on tab-n 
2. refresh the page
3. see that the hash is #tab-n but the active tab is #tab-0

I'm using this code to prevent an ajax tab (#tab-n in this example) not to become the active tab at page load, because it needs data from other tabs to initialize.

**Comment by elboletaire** [comment]
I'll need to dig further into it, because if you take a look to the code the `switch` method tries to write the history, but I see in your example it's not working as expected.

**Comment by tpaksu** [comment]
Yes, there's a little glimpse of the switched tab and then returns back to the original state. IMHO, the history caller works after the init event.

**Comment by tpaksu** [comment]
it might be related with the firstTime flag, because it adds the refreshed page, not the switched one. If we disable the firstTime flag and reenable after full initialization (after onInit() event), this might be fixed..

**Comment by tpaksu** [comment]
Yes it fixed it. And maybe a property for the tabs which should not be a subject of history could be added in this script. That'll be awesome.

**Comment by tpaksu** [comment]
Yes it fixed it. And maybe a property for the tabs which should not be a subject of history could be added in this script. That'll be awesome. 

#32
