### ISSUE TITLE
[Feature] "Better" previous next

### ISSUE THREAD

**Issue by ellisgl** [elboletaire/tabbedcontent#37]
I would like to see a feature that would mimic the  "previous/next" icons like the following ui frameworks:
http://element.eleme.io/#/en-US/component/tabs
http://jqwidgets.com/jquery-widgets-demo/demos/jqxtabs/index.htm
http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#basic-tabs

**Comment by elboletaire** [comment]
Sorry, I don't get this. This plugin actually has `next` and `prev` functionality. What do you mean with `mimic the "previous/next" icons like in that ui frameworks`??

**Comment by elboletaire** [comment]
BTW, the `next` and `prev` tabs styling and icons are up to you. This plugin has the `next` and `prev` actions as API actions, so you can define them as you want.

**Comment by ellisgl** [comment]
In some of the other example I showed you, "Previous/Next" show up as left right arrows on the left and right side of the tab bar. Also the icons don't show up until the tab bar goes into overflow.

**Comment by elboletaire** [comment]
As I answered before in https://github.com/elboletaire/tabbedcontent/issues/19, as you can style the tabs as you want, is up to you if you wanna add some kind of `tabs overflow`/`pagination`/`scroll` plugin to the tabs.

Adding #35 and #36 will be enough to get something similar to the examples you paste (obviously you'll need to select and add your own plugin for the tabs overflow).

I don't want to have this in this plugin, as it would heavily increase the library size and isn't something everyone wants. You better add the plugin you want and style the tabs as required.
